local DDRMSynthControl = {}

function DDRMSynthControl:new(id, name, param, cc, byte, layerByte, layer, mftCh, mftCC, gridX, gridY)
    local o = {
        id = id,
        name = name,
        param = param and ("doubledecker_" .. param) or nil,
        cc = cc,
        byte = byte,
        layerByte = layerByte,
        layer = layer,
        mftCh = mftCh,
        mftCC = mftCC,
        gridX = gridX,
        gridY = gridY,
    }
    setmetatable(o, self)
    self.__index = self
    return o
end

-- you should be able to set multiple "controller devices" - grid, mft, midi, etc.
-- When they recieve control, write through to the appropriate params.
-- When we write to params, interpose something that sends updates to the controller devices.

local CONTROLS = {
    DDRMSynthControl:new("DDRM_SPEED_VCO_1", "Ch I: PWM Speed", "layer_lfo_freq_1", 40, 0, 0, 1),
    DDRMSynthControl:new("DDRM_PWM_VCO_1", "Ch I: PWM Amount", "pwm_1", 41, 1, 1, 1),
    DDRMSynthControl:new("DDRM_PW_VCO_1", "Ch I: PW", "pw_1", 42, 2, 2, 1),
    DDRMSynthControl:new("DDRM_SQR_VCO_1", "Ch I: Square", nil, 43, 73, 24, 1),
    DDRMSynthControl:new("DDRM_SAW_VCO_1", "Ch I: Sawtooth", nil, 44, 74, 25, 1),
    DDRMSynthControl:new("DDRM_NOISE_VCO_1", "Ch I: Noise", "noise_1", 45, 3, 3, 1),
    DDRMSynthControl:new("DDRM_HPF_VCF_1", "Ch I: HPF", "hp_freq_1", 46, 4, 4, 1),
    DDRMSynthControl:new("DDRM_RESh_VCF_1", "Ch I: RESh", "hp_res_1", 47, 5, 5, 1),
    DDRMSynthControl:new("DDRM_LPF_VCF_1", "Ch I: LPF", "lp_freq_1", 48, 6, 6, 1),
    DDRMSynthControl:new("DDRM_RESl_VCF_1", "Ch I: RESl", "lp_res_1", 49, 7, 7, 1),
    DDRMSynthControl:new("DDRM_IL_VCF_1", "Ch I: VCF IL", "filter_init_1", 50, 8, 8, 1),
    DDRMSynthControl:new("DDRM_AL_VCF_1", "Ch I: VCF AL", "filter_attack_level_1", 51, 9, 9, 1),
    DDRMSynthControl:new("DDRM_A_VCF_1", "Ch I: VCF A", "filter_attack_1", 52, 10, 10, 1),
    DDRMSynthControl:new("DDRM_D_VCF_1", "Ch I: VCF D", "filter_decay_1", 53, 11, 11, 1),
    DDRMSynthControl:new("DDRM_R_VCF_1", "Ch I: VCF R", "filter_release_1", 54, 12, 12, 1),
    DDRMSynthControl:new("DDRM_VCF_VCA_1", "Ch I: VCF Level", "filt_1", 55, 13, 13, 1),
    DDRMSynthControl:new("DDRM_SINE__VCA_1", "Ch I: Sine Level", "sine_1", 56, 14, 14, 1),
    DDRMSynthControl:new("DDRM_A_VCA_1", "Ch I: VCA A", "amp_attack_1", 57, 15, 15, 1),
    DDRMSynthControl:new("DDRM_D_VCA_1", "Ch I: VCA D", "amp_decay_1", 58, 16, 16, 1),
    DDRMSynthControl:new("DDRM_S_VCA_1", "Ch I: VCA S", "amp_sustain_1", 59, 17, 17, 1),
    DDRMSynthControl:new("DDRM_R_VCA_1", "Ch I: VCA R", "amp_release_1", 60, 18, 18, 1),
    DDRMSynthControl:new("DDRM_LEVEL_VCA_1", "Ch I: Channel Level", "layer_amp_1", 61, 19, 19, 1),
    DDRMSynthControl:new("DDRM_INIT_BR_TOUCH_1", "Ch I: Initial Brilliance", "velocity_to_filter_1", 62, 20, 20, 1),
    DDRMSynthControl:new("DDRM_INIT_LEV_TOUCH_1", "Ch I: Initial Level", "velocity_to_amp_1", 63, 21, 21, 1),
    DDRMSynthControl:new("DDRM_AT_BR_TOUCH_1", "Ch I: After Brilliance", "pressure_to_filter_1", 65, 22, 22, 1),
    DDRMSynthControl:new("DDRM_AT_LEV_TOUCH_1", "Ch I: After Level", "pressure_to_amp_1", 66, 23, 23, 1),
    DDRMSynthControl:new("DDRM_SPEED_VCO_2", "Ch II: PWM Speed", "layer_lfo_freq_2", 67, 30, 0, 2),
    DDRMSynthControl:new("DDRM_PWM_VCO_2", "Ch II: PWM Amount", "pwm_2", 68, 31, 1, 2),
    DDRMSynthControl:new("DDRM_PW_VCO_2", "Ch II: PW", "pw_2", 69, 32, 2, 2),
    DDRMSynthControl:new("DDRM_SQR_VCO_2", "Ch II: Square", nil, 71, 76, 24, 2),
    DDRMSynthControl:new("DDRM_SAW_VCO_2", "Ch II: Sawtooth", nil, 70, 75, 25, 2),
    DDRMSynthControl:new("DDRM_NOISE_VCO_2", "Ch II: Noise", "noise_2", 72, 33, 3, 2),
    DDRMSynthControl:new("DDRM_HPF_VCF_2", "Ch II: HPF", "hp_freq_2", 73, 34, 4, 2),
    DDRMSynthControl:new("DDRM_RESh_VCF_2", "Ch II: RESh", "hp_res_2", 119, 35, 5, 2),
    DDRMSynthControl:new("DDRM_LPF_VCF_2", "Ch II: LPF", "lp_freq_2", 75, 36, 6, 2),
    DDRMSynthControl:new("DDRM_RESl_VCF_2", "Ch II: RESl", "lp_res_2", 76, 37, 7, 2),
    DDRMSynthControl:new("DDRM_IL_VCF_2", "Ch II: VCF IL", "filter_init_2", 77, 38, 8, 2),
    DDRMSynthControl:new("DDRM_AL_VCF_2", "Ch II: VCF AL", "filter_attack_level_2", 78, 39, 9, 2),
    DDRMSynthControl:new("DDRM_A_VCF_2", "Ch II: VCF A", "filter_attack_2", 79, 24, 10, 2),
    DDRMSynthControl:new("DDRM_D_VCF_2", "Ch II: VCF D", "filter_decay_2", 80, 25, 11, 2),
    DDRMSynthControl:new("DDRM_R_VCF_2", "Ch II: VCF R", "filter_release_2", 81, 26, 12, 2),
    DDRMSynthControl:new("DDRM_VCF_VCA_2", "Ch II: VCF Level", "filt_2", 82, 27, 13, 2),
    DDRMSynthControl:new("DDRM_SINE__VCA_2", "Ch II: Sine Level", "sine_2", 83, 28, 14, 2),
    DDRMSynthControl:new("DDRM_A_VCA_2", "Ch II: VCA A", "amp_attack_2", 84, 29, 15, 2),
    DDRMSynthControl:new("DDRM_D_VCA_2", "Ch II: VCA D", "amp_decay_2", 85, 40, 16, 2),
    DDRMSynthControl:new("DDRM_S_VCA_2", "Ch II: VCA S", "amp_sustain_2", 86, 41, 17, 2),
    DDRMSynthControl:new("DDRM_R_VCA_2", "Ch II: VCA R", "amp_release_2", 87, 42, 18, 2),
    DDRMSynthControl:new("DDRM_LEVEL_VCA_2", "Ch II: Channel Level", "layer_2", 88, 43, 19, 2),
    DDRMSynthControl:new("DDRM_INIT_BR_TOUCH_2", "Ch II: Initial Brilliance", "velocity_to_filter_2", 89, 44, 20, 2),
    DDRMSynthControl:new("DDRM_INIT_LEV_TOUCH_2", "Ch II: Initial Level", "velocity_to_amp_2", 90, 45, 21, 2),
    DDRMSynthControl:new("DDRM_AT_BR_TOUCH_2", "Ch II: After Brilliance", "pressure_to_filter_2", 91, 46, 22, 2),
    DDRMSynthControl:new("DDRM_AT_LEV_TOUCH_2", "Ch II: After Level", "pressure_to_amp_2", 92, 47, 23, 2),
    DDRMSynthControl:new("DDRM_COARSE_PITCH", "Ch : Pitch Coarse", nil, 93, 77, -1, 0, false),
    DDRMSynthControl:new("DDRM_FINE_PITCH", "Ch : Pitch Fine", 94, nil, 78, -1, 0, false),
    DDRMSynthControl:new("DDRM_DETUNE_CH2_PITCH", "Ch : Detune Ch II", "detune", 95, 79, -1, 0),
    DDRMSynthControl:new("DDRM_FEET_1_FEET", "Ch : Feet I", "pitch_ratio_1", 102, 48, -1, 0),
    DDRMSynthControl:new("DDRM_FEET_2_FEET", "Ch : Feet II", "pitch_ratio_2", 103, 49, -1, 0),
    DDRMSynthControl:new("DDRM_FUNCTION_SUB_OSC", "Ch : Sub Osc Function", nil, 104, 50, -1, 0),
    DDRMSynthControl:new("DDRM_SPEED_SUB_OSC", "Ch : Sub Osc Speed", "lfo_rate", 105, 51, -1, 0),
    DDRMSynthControl:new("DDRM_VCO_SUB_OSC", "Ch : Sub Osc VCO Amount", "lfo_to_freq", 106, 52, -1, 0),
    DDRMSynthControl:new("DDRM_VCF_SUB_OSC", "Ch : Sub Osc VCF Amount", "lfo_to_filter", 107, 53, -1, 0),
    DDRMSynthControl:new("DDRM_VCA_SUB_OSC", "Ch : Sub Osc VCA Amount", "lfo_to_amp", 108, 54, -1, 0),
    DDRMSynthControl:new("DDRM_MIX", "Ch : Mix", "mix", 8, 55, -1, 0),
    DDRMSynthControl:new("DDRM_BRILL", "Ch : Brilliance", "brilliance", 109, 56, -1, 0),
    DDRMSynthControl:new("DDRM_RESSO", "Ch : Ressonance", "resonance", 110, 57, -1, 0),
    DDRMSynthControl:new("DDRM_INITIAL_TOUCH", "Ch : Initial Pitch Bend", "pitch_env", 111, 58, -1, 0),
    DDRMSynthControl:new("DDRM_SPEED_TOUCH", "Ch : Touch Response Sub Osc Speed", "lfo_pres_to_freq", 112, 59, -1, 0),
    DDRMSynthControl:new("DDRM_VCO_TOUCH", "Ch : Touch Response Sub Osc VCO Amount", "lfo_pres_to_vibrato", 113, 60, -1, 0),
    DDRMSynthControl:new("DDRM_VCF_TOUCH", "Ch : Touch Response Sub Osc VCF Amount", "lfo_pres_to_filt", 114, 61, -1, 0),
    DDRMSynthControl:new("DDRM_BR_LOW_KBRD", "Ch : Brilliance Low", nil, 115, 62, -1, 0),
    DDRMSynthControl:new("DDRM_BR_HIGH_KBRD", "Ch : Brilliance High", nil, 116, 63, -1, 0),
    DDRMSynthControl:new("DDRM_LEV_LOW_KBRD", "Ch : Level Low", nil, 117, 64, -1, 0),
    DDRMSynthControl:new("DDRM_LEV_HIGH_KBRD", "Ch : Level High", nil, 118, 65, -1, 0),
    DDRMSynthControl:new("DDRM_GLIDE_MODE_GLIDE", "Ch : Glide Mode", nil, 39, -1, -1, 0),
    DDRMSynthControl:new("DDRM_GLIDE_TIME_GLIDE", "Ch : Glide Time", "portomento", 5, 66, -1, 0),
    DDRMSynthControl:new("DDRM_SUSTAIN_MODE", "Ch : Sustain Mode", nil, 9, -1, -1, 0, false),
    DDRMSynthControl:new("DDRM_SUSTAIN_TIME", "Ch : Sustain Time", nil, 11, -1, -1, 0, false),
}
